# Generated by Django 4.2.2 on 2023-10-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_limitdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
